name: Android CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'


      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: |
          {
            echo 'org.gradle.caching=true'
            echo 'org.gradle.parallel=true'
            echo 'org.gradle.vfs.watch=true'
            echo 'org.gradle.jvmargs=-Xmx2048m'
          } >> gradle.properties
          ./gradlew --no-daemon --warning-mode=all publishToMavenLocal
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.maven_pgp_signingKey }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.maven_pgp_signingPassword }}

      - name: Upload library
        uses: actions/upload-artifact@v4
        with:
          name: library
          path: ~/.m2/repository

      - name: Prepare pages
        run: |
          mkdir -p docs
          cp -r helper/build/intermediates/java_doc_dir/release/* docs/
          mkdir -p docs/ktx
          cp -r helper-ktx/build/intermediates/java_doc_dir/release/* docs/ktx

      - name: Upload pages
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        continue-on-error: true
        uses: actions/deploy-pages@v4
